apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myekscluster
  region: ap-south-1

nodeGroups:
   - name: ng1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: neokey
   - name: ng2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: neokey
   - name: ng-mixed
     minSize: 1
     maxSize: 2
     instancesDistribution:
       maxPrice: 0.025
       instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 50
       spotInstancePools: 2     
     ssh:
         publicKeyName: neokey
